name: "Klare"
description: "Thoughts from a designer/developer"

author: "Klare Frank"

url: "http://kfrank.github.io/klare"
baseurl: "http://kfrank.github.io/klare"

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: http://kfrank.github.io/klare
ga_tracking_id: UA-49926701-1
