# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Klare Frank
email: klaredelune+io@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Klare is a digital product designer based in Seattle doing ux, ui, illustration, and frontend development.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: :title.html
url: "http://klare.io" # the base hostname & protocol for your site
twitter_username: klare
github_username:  kfrank

# Build settings
markdown: kramdown
encoding: utf-8
