name: "Klare"
description: "Thoughts from a designer/developer"

author: "Klare Frank"

url: "/"
baseurl: ""

markdown: rdiscount
permalink: :title.html
highlighter: true

# Google Analytics
ga_domain: http://klare.io
ga_tracking_id: UA-49926701-1

